name: 'CI/CD pipeline for terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

      env:
       AWS_REGION: us-east-1
       TF_VAR_key_name: ${{ secrets.EC2_KEY_NAME }}     # ← your "secondary account" key
       TF_VAR_ami_id: ${{ secrets.EC2_AMI_ID }}         # ← ami-00c5d42fcb71673fd


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    # Initialize terraform 
    - name: Terraform Init stage
      run: terraform init

    # check the terraform format
    - name: Terraform Format check
      run: terraform fmt -check

    #execution plan for Terraform
    - name: view the terraform plan
      run: terraform plan -input=false
# terraform aplly is auto approved  
    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
     # Terraform Output
    - name: Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform output
